language: java
jdk:
- oraclejdk8
install: true
script:
  - mvn clean install -P-embedded
  - if [ "$TRAVIS_TAG" != "" ]; then
      mvn deploy -DskipTests --settings .travis.settings.xml;
    fi
services:
- mongodb
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^release-[0-9]+\.[0-9]+\.[0-9]+/
env:
  global:
  - secure: kWP2/Xhd+DvGW03tkJ01Ws9j+DxJPs6A4D0g7PCANTb8AcGmoI6G7ErdcrMh7fon0yPgU6sXImZlq/Og2xXwGIxvngdArH0v8bvQ9Y6+KU4or/WLXfHTIHEUS/FElTn8ljlsnz3el4B+y5aPo4gK2Qvql7DHMwx1bX65A6X+YdTYMjjgGFYPRtn38yPxt6YW0hJVCQYbsGTysrguaIKQGaCLAWixYqpd4UxchMCi0yg1IkuiXTajQjnUfANO2XrJ0kGg9U7X3xb9o+p18x+n+J2Yc1K/ldLDJR1BXGq34pb0DxjzfB5Kq8tvdcG0RI694H6Po+TFqzv4AGXVu7OldF6OH/dpL68ts56g+VVQ9Kafjt2HZNoMKJqgv9bu/Bh2f+pTihfsS2nxCJ2zobMdGAPO42pHJD6AEbZ/XYS5ml9ZEqRPnQWAHmeRaNSXzsJp4cCz15PiW5LygSGm79VLtcNlHCK2RNk1kWon9LSYVlVDe7BQwUgGCx89J06qw+DoH1rpNoi50Oj+BLybM/chVE5rIjFHn1ZHZhQiLQM01GYft7CUz/2OA0+H2ndFngcf9f4JZO9TrHONlmDXpn9O5NuJDZBuYOrmjpB0yk64pck/GtsFNkVT0NKGvO2rbI1ChtbIYWPqdAA2MGdZ9E6FotTaCo/62mRewudPvGJ3770=
  - secure: I/OUH4r75ZrUIfpgjA3HNPQI3Wgw+Wm/XaqDcVclAOjcz1yP4yP0an8HXHQXh1nUQ/yz2e0SmR3+G3MOHAmtrOpSv0Hool34d8mHjS61LjrYqhsRbYgE/S7UL5/epdIAEtQCxfD7+cdyOIuSr5vGgmvYoacZymc/SL3z1K4pOpTzmJD4Fm8+X5pw3+ai4TVJHR7bLAEPm/uO+OPzZdzGIKOTKnviYE9f8OixgPXkig9E1k4cPLhBlbbmtVKTEtlqcifnY48/SSyLuXTye3/rT4neARkT2Q0RZIAhYvOggxwNTJF+57zf4NoLbugvyX/irftQUPuCsyZ25NMTyANDymfw/U05Rs1FeqblkZgaIz12HkRoxX/3uIefK6HZwU/3HzLOEV8wHnMSNiru+elUcBghdpIL90eMskpaSXo27b/A/97wTPOQpwhYvk9Fd7LhjeP+i7Bghv6fk+eaeUx2QTnvejva3rocR10i8jr2S5lIpUwzAvURBPeg80XPqPdXm4OwPTE+XWcTohj9iKdanoIZNzZ5L7Je3rvcRy0W3bZTY1is+EJA+D2E0aiEK0XJ5ulFi4qVT3EuPfOCwecCdXp8uBlJQcn/YaVvDdWWntgkY6ZTk2C+LpdhvFqI2+mlUcrmwEEkgxWa27Pg8Zb+BSkYwQORVlHMh43tN2s3Ee4=
